export const LOGS_VIDEO = "https://www.youtube.com/embed/N94Q0SmpXig?si=8WUI07cry7MjToHn"
export const CALENDER_VIDEO = "https://www.youtube.com/embed/N94Q0SmpXig?si=8WUI07cry7MjToHn"
export const SYSTEM_DATA_VIDEO = "https://www.youtube.com/embed/dQw4w9WgXcQ"
export const DEVICES_VIDEO = "https://www.youtube.com/embed/dQw4w9WgXcQ"
export const ATTENDANCE_VIDEO = "https://www.youtube.com/embed/dQw4w9WgXcQ"
export const ATTENDANCE_OVERVIEW_VIDEO = "https://www.youtube.com/embed/dQw4w9WgXcQ"
export const ATTENDANCE_VACATION_VIDEO = "https://www.youtube.com/embed/dQw4w9WgXcQ"