export { default as ManageDevicesPage } from "./manage-devices"
export { default as LogsPage } from "./manage-logs"
export { default as SystemDataPage } from "./manage-system-data"
export * from "./manage-profiles"
export { default as ManagePermissionsPage } from "./manage-permissions"
export { default as ManageOfficialVacationsPage } from "./manage-official-vacation"
export { default as ManageEntitiesPage } from "./manage-entities"
export { default as ManageDepartmentsPage } from "./manage-departments"
export { default as ManageSubDepartmentsPage } from "../common/manage-sub-departments"
export * from "../common/manage-attendance"
export * from "../common/manage-employees"
export * from "../common/manage-managers"
export { default as CalendarPage } from "../common/Calender"
export { default as AdminAccountPage } from "./Account"
export * from "./manage-admins"
export { default as MoveUserAttendancePage } from "./moveUserAttendance"